version: '3.3'

networks:
  app-tier:
    driver: bridge

services:
  mongo_db:
    image: mongo:latest
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - app-tier

  eventApp:
    image: event
    depends_on:
      - mongo_db
    ports:
      - 9090:9090
    environment:
      kafka.bootstrapAddress: kafka:9092
      kafka.employeeEvent.topic.name: employee-event-v1
      kafka.groupId: cg1
      spring.data.mongodb.uri: mongodb://mongo_db:27017

    networks:
      - app-tier
# Names our volume
volumes:
  my-db: